RRA.MVC.UI/Models/AccountActivationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RRA.MVC.UI.Models
{
    public class AccountActivationModel
    {
        public int UserId { get; set; }
        public bool IsActivated { get; set; }
        public DateTime AccountActivatedDate { get; set; }
    }
}

RRA.MVC.UI/Models/ErrorViewModel.cs
using System;

namespace RRA.MVC.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RRA.MVC.UI/Models/User.cs
using System;

namespace RRA.MVC.UI.Models
{
    public class User
    {
        public int? Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
    }
}

RRA.MVC.UI/Models/UserPasswordModel.cs
namespace RRA.MVC.UI.Models
{
    public class UserPasswordModel
    {
        public int UserId { get; set; }
        public string Password { get; set; }
    }
}

RRA.MVC.UI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace RRA.MVC.UI.Controllers
{
    [Route("account")]
    public class AccountController : Controller
    {
    
        [Route("login")]
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            if (username != null && password != null && username.Equals("acc1") && password.Equals("123"))
            {
                HttpContext.Session.SetString("username", username);
                return View("Success");
            }
            else
            {
                ViewBag.error = "Invalid Account";
                return View("Index");
            }
        }

        [Route("logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Index");
        }
    }
}

RRA.MVC.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RRA.MVC.UI.Models;

namespace RRA.MVC.UI.Controllers
{
    public class HomeController : Controller
    {



        public HomeController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RRA.MVC.UI/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RRA.MVC.UI.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Registration()
        {
            return View();
        }
    }
}

RRA.MVC.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<p>@ViewBag.loggedinUser</p>

RRA.MVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="~/lib/Materialize/css/materialize.min.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="teal darken-4 lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="/" class="brand-logo">
                    <i class="material-icons">
                        touch_app
                    </i> E-TAX
                </a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#">Login</a></li>
                    <li><a asp-area="" asp-controller="Registration" asp-action="Registration">Registration</a></li>
                    <li><a href="#">@User.Identity.Name</a></li>
                </ul>

                <ul id="nav-mobile" class="sidenav">
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Registration</a></li>
                    <li><a href="#">@User.Identity.Name</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </nav>
    </header>
    <div class="container" id="body-container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - RRA E-Tax - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
    </environment>

    <!-- Compiled and minified JavaScript -->
    <script src="~/lib/Materialize/js/materialize.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>